all_stations_dict = {
    'w01': 'national_stadium',
    
    'cen': 'siam',
    
    's01': 'ratchadamri',
    's02': 'sala_daeng',
    's03': 'chong_nonsi',
    's04': 'saint_louis',
    's05': 'surasak',
    's06': 'saphan_taksin',
    's07': 'krung_thon_buri',
    's08': 'wongwian_yai',
    's09': 'pho_nimit',
    's10': 'talat_phlu',
    's11': 'wutthakat',
    's12': 'bang_wa',
    
    'g01': 'krung_thon_buri',
    'g02': 'charoen_nakhon',
    'g03': 'khlong_san',
    
    'e01': 'chit_lom',
    'e02': 'phloen_chit',
    'e03': 'nana',
    'e04': 'asok',
    'e05': 'phrom_phong',
    'e06': 'thong_lo',
    'e07': 'ekkamai',
    'e08': 'phra_khanong',
    'e09': 'on_nut',
    'e10': 'bang_chak',
    'e11': 'punnawithi',
    'e12': 'udom_suk',
    'e13': 'bang_na',
    'e14': 'bearing',
    'e15': 'samrong',
    'e16': 'pu_chao',
    'e17': 'chang_erawan',
    'e18': 'royal_thai_naval_academy',
    'e19': 'pak_nam',
    'e20': 'srinagarindra',
    'e21': 'phraek_sa',
    'e22': 'sai_luat',
    'e23': 'kheha',
    
    'n01': 'ratchathewi',
    'n02': 'phaya_thai_bts',
    'n03': 'victory_monument',
    'n04': 'sanam_pao',
    'n05': 'ari',
    'n07': 'saphan_khwai',
    'n08': 'mo_chit',
    'n09': 'ha_yaek_lat_phrao',
    'n10': 'phahon_yothin24',
    'n11': 'ratchayothin',
    'n12': 'sena_nikhom',
    'n13': 'kasetsart_university',
    'n14': 'royal_forest_department',
    'n15': 'bang_bua',
    'n16': '11th_infantry_regiment',
    'n17': 'wat_phra_sri_mahathat_bts',
    'n18': 'phahon_yothin59',
    'n19': 'sai_yud',
    'n20': 'saphan_mai',
    'n21': 'bhumibol_adulyadej_hospital',
    'n22': 'royal_thai_air_force_museum',
    'n23': 'yaek_kor_por_aor',
    'n24': 'khu_khot',
    
    'pp01': 'khlog_bang_phai',
    'pp02': 'talad_bang_yai',
    'pp03': 'sam_yaek_bang_yai',
    'pp04': 'bang_phlu',
    'pp05': 'bang_rak_yai',
    'pp06': 'bang_rak_noi_tha_it',
    'pp07': 'sai_ma',
    'pp08': 'phra_nang_klao_bridge',
    'pp09': 'yaek_nonthaburi1',
    'pp10': 'bang_krasor',
    'pp11': 'nonthaburi_civic_center_pp',
    'pp12': 'ministry_of_public_health',
    'pp13': 'yaek_tiwanon',
    'pp14': 'wong_sawang',
    'pp15': 'bang_son_pp',
    'pp16': 'tao_poon_pp',
    
    'bl01': 'tha_phra',
    'bl02': 'charan13',
    'bl03': 'fai_chai',
    'bl04': 'bang_khun_non',
    'bl05': 'bang_yi_khan',
    'bl06': 'sirindhorn',
    'bl07': 'bang_phlat',
    'bl08': 'bang_o',
    'bl09': 'bang_pho',
    'bl10': 'tao_poon_mrt',
    'bl11': 'bang_sue',
    'bl12': 'kamphaeng_phet',
    'bl13': 'chatuchak_park',
    'bl14': 'phahon_yothin',
    'bl15': 'lat_phrao_mrt',
    'bl16': 'ratchadaphisek',
    'bl17': 'sutthisan',
    'bl18': 'huai_khwang',
    'bl19': 'thailand_cultural_centre',
    'bl20': 'phra_ram9',
    'bl21': 'phetchaburi',
    'bl22': 'sukhumvit',
    'bl23': 'queen_sirikit_national_covention_centre',
    'bl24': 'khlog_toei',
    'bl25': 'lumphini',
    'bl26': 'si_lom',
    'bl27': 'sam_yan',
    'bl28': 'hua_lamphong',
    'bl29': 'wat_mangkon',
    'bl30': 'sam_yot',
    'bl31': 'sanam_chai',
    'bl32': 'itsaraphap',
    'bl33': 'bang_phai',
    'bl34': 'bang_wa_pier',
    'bl35': 'phetkasem48',
    'bl36': 'phasi_charoen',
    'bl37': 'bang_khae',
    'bl38': 'lak_song',
    
    'a08': 'phaya_thai_arl',
    'a07': 'ratchaprarop',
    'a06': 'makkasan',
    'a05': 'ramkhamhaeng',
    'a04': 'hua_mak_arl',
    'a03': 'ban_thap_chang',
    'a02': 'lat_krabang',
    'a01': 'suvarnabhumi',
    
    'pk01' : 'nonthaburi_civic_center_pk',
    'pk02' : 'khae_rai',
    'pk03' : 'sanambin_nam',
    'pk04' : 'samakkhi',
    'pk05' : 'royal_irrigation_department',
    'pk06' : 'yaek_pak_kret',
    'pk07' : 'pak_kret_bypass',
    'pk08' : 'chaeng_watthana_pak_kret_28',
    'pk09' : 'si_rat',
    'pk10' : 'muang_thong_thani',
    'pk11' : 'chaeng_watthana_14',
    'pk12' : 'government_complex',
    'pk13' : 'national_telecom',
    'pk14' : 'lak_si_PK',
    'pk15' : 'rajabhat_phranakhon',
    'pk16' : 'wat_phra_sri_mahathat_pk',
    'pk17' : 'ram_inthra_3',
    'pk18' : 'lat_pla_khao',
    'pk19' : 'ram_inthra_kor_mor_4',
    'pk20' : 'maiyalap',
    'pk21' : 'vacharaphol',
    'pk22' : 'ram_inthra_kor_mor_6',
    'pk23' : 'khu_bon',
    'pk24' : 'ram_inthra_kor_mor_9',
    'pk25' : 'outer_ring_road_ram_inthra',
    'pk26' : 'nopparat',
    'pk27' : 'bang_chan',
    'pk28' : 'setthabutbamphen',
    'pk29' : 'min_buri_market',
    'pk30' : 'min_buri',
    
    'yl01': 'lat_phrao_yl',
    'yl02': 'phawana',
    'yl03': 'chok_chai4',
    'yl04': 'lat_phrao71',
    'yl05': 'lat_phrao83',
    'yl06': 'mahat_thai',
    'yl07': 'lat_phrao101',
    'yl08': 'bang_kapi',
    'yl09': 'yaek_lam_sali',
    'yl10': 'si_kritha',
    'yl11': 'hua_mak_YL',
    'yl12': 'kalantan',
    'yl13': 'si_nut',
    'yl14': 'srinagarindra38',
    'yl15': 'suan_luang_rama9',
    'yl16': 'si_udom',
    'yl17': 'si_iam',
    'yl18': 'si_la_salle',
    'yl19': 'si_bearing',
    'yl20': 'si_dan',
    'yl21': 'si_thepha',
    'yl22': 'thipphawan',
    'yl23': 'samrong',
    
    'rw01': 'krung_thep_apiwat_rw',
    'rw02': 'bang_son_RW',
    'rw03': 'bang_bamru',
    'rw04': 'talingchan',
    
    'rn01': 'krung_thep_apiwat_rn',
    'rn02': 'chatuchak',
    'rn03': 'wat_samian_nari',
    'rn04': 'bang_khen',
    'rn05': 'thung_song_hong',
    'rn06': 'lak_si_RN',
    'rn07': 'kan_kheha',
    'rn08': 'don_mueang',
    'rn09': 'lak_hok',
    'rn10': 'rangsit',
}
